// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MotorCommands.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__MOTORCOMMANDS_HPP
#define FAST_DDS_GENERATED__MOTORCOMMANDS_HPP

#include <cstdint>
#include <utility>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(MOTORCOMMANDS_SOURCE)
#define MOTORCOMMANDS_DllAPI __declspec( dllexport )
#else
#define MOTORCOMMANDS_DllAPI __declspec( dllimport )
#endif // MOTORCOMMANDS_SOURCE
#else
#define MOTORCOMMANDS_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define MOTORCOMMANDS_DllAPI
#endif // _WIN32

/*!
 * @brief This class represents the structure MotorCommands defined by the user in the IDL file.
 * @ingroup MotorCommands
 */
class MotorCommands
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport MotorCommands()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~MotorCommands()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object MotorCommands that will be copied.
     */
    eProsima_user_DllExport MotorCommands(
            const MotorCommands& x)
    {
                    m_sec = x.m_sec;

                    m_nanosec = x.m_nanosec;

                    m_duty_cycle = x.m_duty_cycle;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object MotorCommands that will be copied.
     */
    eProsima_user_DllExport MotorCommands(
            MotorCommands&& x) noexcept
    {
        m_sec = x.m_sec;
        m_nanosec = x.m_nanosec;
        m_duty_cycle = x.m_duty_cycle;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object MotorCommands that will be copied.
     */
    eProsima_user_DllExport MotorCommands& operator =(
            const MotorCommands& x)
    {

                    m_sec = x.m_sec;

                    m_nanosec = x.m_nanosec;

                    m_duty_cycle = x.m_duty_cycle;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object MotorCommands that will be copied.
     */
    eProsima_user_DllExport MotorCommands& operator =(
            MotorCommands&& x) noexcept
    {

        m_sec = x.m_sec;
        m_nanosec = x.m_nanosec;
        m_duty_cycle = x.m_duty_cycle;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x MotorCommands object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const MotorCommands& x) const
    {
        return (m_sec == x.m_sec &&
           m_nanosec == x.m_nanosec &&
           m_duty_cycle == x.m_duty_cycle);
    }

    /*!
     * @brief Comparison operator.
     * @param x MotorCommands object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const MotorCommands& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member sec
     * @param _sec New value for member sec
     */
    eProsima_user_DllExport void sec(
            int32_t _sec)
    {
        m_sec = _sec;
    }

    /*!
     * @brief This function returns the value of member sec
     * @return Value of member sec
     */
    eProsima_user_DllExport int32_t sec() const
    {
        return m_sec;
    }

    /*!
     * @brief This function returns a reference to member sec
     * @return Reference to member sec
     */
    eProsima_user_DllExport int32_t& sec()
    {
        return m_sec;
    }


    /*!
     * @brief This function sets a value in member nanosec
     * @param _nanosec New value for member nanosec
     */
    eProsima_user_DllExport void nanosec(
            int32_t _nanosec)
    {
        m_nanosec = _nanosec;
    }

    /*!
     * @brief This function returns the value of member nanosec
     * @return Value of member nanosec
     */
    eProsima_user_DllExport int32_t nanosec() const
    {
        return m_nanosec;
    }

    /*!
     * @brief This function returns a reference to member nanosec
     * @return Reference to member nanosec
     */
    eProsima_user_DllExport int32_t& nanosec()
    {
        return m_nanosec;
    }


    /*!
     * @brief This function sets a value in member duty_cycle
     * @param _duty_cycle New value for member duty_cycle
     */
    eProsima_user_DllExport void duty_cycle(
            float _duty_cycle)
    {
        m_duty_cycle = _duty_cycle;
    }

    /*!
     * @brief This function returns the value of member duty_cycle
     * @return Value of member duty_cycle
     */
    eProsima_user_DllExport float duty_cycle() const
    {
        return m_duty_cycle;
    }

    /*!
     * @brief This function returns a reference to member duty_cycle
     * @return Reference to member duty_cycle
     */
    eProsima_user_DllExport float& duty_cycle()
    {
        return m_duty_cycle;
    }



private:

    int32_t m_sec{0};
    int32_t m_nanosec{0};
    float m_duty_cycle{0.0};

};

#endif // _FAST_DDS_GENERATED_MOTORCOMMANDS_HPP_


