// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ToFData.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "ToFData.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

ToFData::ToFData()
{
    // m_sec com.eprosima.idl.parser.typecode.PrimitiveTypeCode@12f41634
    m_sec = 0;
    // m_nanosec com.eprosima.idl.parser.typecode.PrimitiveTypeCode@13c27452
    m_nanosec = 0;
    // m_distance com.eprosima.idl.parser.typecode.PrimitiveTypeCode@262b2c86
    m_distance = 0.0;

}

ToFData::~ToFData()
{


}

ToFData::ToFData(
        const ToFData& x)
{
    m_sec = x.m_sec;
    m_nanosec = x.m_nanosec;
    m_distance = x.m_distance;
}

ToFData::ToFData(
        ToFData&& x) noexcept 
{
    m_sec = x.m_sec;
    m_nanosec = x.m_nanosec;
    m_distance = x.m_distance;
}

ToFData& ToFData::operator =(
        const ToFData& x)
{

    m_sec = x.m_sec;
    m_nanosec = x.m_nanosec;
    m_distance = x.m_distance;

    return *this;
}

ToFData& ToFData::operator =(
        ToFData&& x) noexcept
{

    m_sec = x.m_sec;
    m_nanosec = x.m_nanosec;
    m_distance = x.m_distance;

    return *this;
}

bool ToFData::operator ==(
        const ToFData& x) const
{

    return (m_sec == x.m_sec && m_nanosec == x.m_nanosec && m_distance == x.m_distance);
}

bool ToFData::operator !=(
        const ToFData& x) const
{
    return !(*this == x);
}

size_t ToFData::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t ToFData::getCdrSerializedSize(
        const ToFData& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void ToFData::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_sec;
    scdr << m_nanosec;
    scdr << m_distance;

}

void ToFData::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_sec;
    dcdr >> m_nanosec;
    dcdr >> m_distance;
}

/*!
 * @brief This function sets a value in member sec
 * @param _sec New value for member sec
 */
void ToFData::sec(
        int32_t _sec)
{
    m_sec = _sec;
}

/*!
 * @brief This function returns the value of member sec
 * @return Value of member sec
 */
int32_t ToFData::sec() const
{
    return m_sec;
}

/*!
 * @brief This function returns a reference to member sec
 * @return Reference to member sec
 */
int32_t& ToFData::sec()
{
    return m_sec;
}

/*!
 * @brief This function sets a value in member nanosec
 * @param _nanosec New value for member nanosec
 */
void ToFData::nanosec(
        int32_t _nanosec)
{
    m_nanosec = _nanosec;
}

/*!
 * @brief This function returns the value of member nanosec
 * @return Value of member nanosec
 */
int32_t ToFData::nanosec() const
{
    return m_nanosec;
}

/*!
 * @brief This function returns a reference to member nanosec
 * @return Reference to member nanosec
 */
int32_t& ToFData::nanosec()
{
    return m_nanosec;
}

/*!
 * @brief This function sets a value in member distance
 * @param _distance New value for member distance
 */
void ToFData::distance(
        float _distance)
{
    m_distance = _distance;
}

/*!
 * @brief This function returns the value of member distance
 * @return Value of member distance
 */
float ToFData::distance() const
{
    return m_distance;
}

/*!
 * @brief This function returns a reference to member distance
 * @return Reference to member distance
 */
float& ToFData::distance()
{
    return m_distance;
}


size_t ToFData::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool ToFData::isKeyDefined()
{
    return false;
}

void ToFData::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
       
}
