// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ToFData.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_TOFDATA_H_
#define _FAST_DDS_GENERATED_TOFDATA_H_


#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(ToFData_SOURCE)
#define ToFData_DllAPI __declspec( dllexport )
#else
#define ToFData_DllAPI __declspec( dllimport )
#endif // ToFData_SOURCE
#else
#define ToFData_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define ToFData_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


/*!
 * @brief This class represents the structure ToFData defined by the user in the IDL file.
 * @ingroup TOFDATA
 */
class ToFData
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport ToFData();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~ToFData();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object ToFData that will be copied.
     */
    eProsima_user_DllExport ToFData(
            const ToFData& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object ToFData that will be copied.
     */
    eProsima_user_DllExport ToFData(
            ToFData&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object ToFData that will be copied.
     */
    eProsima_user_DllExport ToFData& operator =(
            const ToFData& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object ToFData that will be copied.
     */
    eProsima_user_DllExport ToFData& operator =(
            ToFData&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x ToFData object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const ToFData& x) const;

    /*!
     * @brief Comparison operator.
     * @param x ToFData object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const ToFData& x) const;

    /*!
     * @brief This function sets a value in member sec
     * @param _sec New value for member sec
     */
    eProsima_user_DllExport void sec(
            int32_t _sec);

    /*!
     * @brief This function returns the value of member sec
     * @return Value of member sec
     */
    eProsima_user_DllExport int32_t sec() const;

    /*!
     * @brief This function returns a reference to member sec
     * @return Reference to member sec
     */
    eProsima_user_DllExport int32_t& sec();

    /*!
     * @brief This function sets a value in member nanosec
     * @param _nanosec New value for member nanosec
     */
    eProsima_user_DllExport void nanosec(
            int32_t _nanosec);

    /*!
     * @brief This function returns the value of member nanosec
     * @return Value of member nanosec
     */
    eProsima_user_DllExport int32_t nanosec() const;

    /*!
     * @brief This function returns a reference to member nanosec
     * @return Reference to member nanosec
     */
    eProsima_user_DllExport int32_t& nanosec();

    /*!
     * @brief This function sets a value in member distance
     * @param _distance New value for member distance
     */
    eProsima_user_DllExport void distance(
            float _distance);

    /*!
     * @brief This function returns the value of member distance
     * @return Value of member distance
     */
    eProsima_user_DllExport float distance() const;

    /*!
     * @brief This function returns a reference to member distance
     * @return Reference to member distance
     */
    eProsima_user_DllExport float& distance();


    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
            const ToFData& data,
            size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(
            eprosima::fastcdr::Cdr& cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(
            eprosima::fastcdr::Cdr& cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(
            eprosima::fastcdr::Cdr& cdr) const;

private:

    int32_t m_sec;
    int32_t m_nanosec;
    float m_distance;
};

#endif // _FAST_DDS_GENERATED_TOFDATA_H_