# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if __import__('os').name == 'nt': import win32api; win32api.LoadLibrary('MotorCommands.dll')
if __package__ or '.' in __name__:
    from . import _MotorCommandsWrapper
else:
    import _MotorCommandsWrapper

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _MotorCommandsWrapper.delete_SwigPyIterator

    def value(self):
        return _MotorCommandsWrapper.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _MotorCommandsWrapper.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _MotorCommandsWrapper.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _MotorCommandsWrapper.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _MotorCommandsWrapper.SwigPyIterator_equal(self, x)

    def copy(self):
        return _MotorCommandsWrapper.SwigPyIterator_copy(self)

    def next(self):
        return _MotorCommandsWrapper.SwigPyIterator_next(self)

    def __next__(self):
        return _MotorCommandsWrapper.SwigPyIterator___next__(self)

    def previous(self):
        return _MotorCommandsWrapper.SwigPyIterator_previous(self)

    def advance(self, n):
        return _MotorCommandsWrapper.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _MotorCommandsWrapper.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _MotorCommandsWrapper.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _MotorCommandsWrapper.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _MotorCommandsWrapper.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _MotorCommandsWrapper.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _MotorCommandsWrapper.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _MotorCommandsWrapper:
_MotorCommandsWrapper.SwigPyIterator_swigregister(SwigPyIterator)
FASTCDR_VERSION_MAJOR = _MotorCommandsWrapper.FASTCDR_VERSION_MAJOR
FASTCDR_VERSION_MINOR = _MotorCommandsWrapper.FASTCDR_VERSION_MINOR
FASTCDR_VERSION_MICRO = _MotorCommandsWrapper.FASTCDR_VERSION_MICRO
FASTCDR_VERSION_STR = _MotorCommandsWrapper.FASTCDR_VERSION_STR
HAVE_CXX11 = _MotorCommandsWrapper.HAVE_CXX11
FASTCDR_IS_BIG_ENDIAN_TARGET = _MotorCommandsWrapper.FASTCDR_IS_BIG_ENDIAN_TARGET
FASTCDR_HAVE_FLOAT128 = _MotorCommandsWrapper.FASTCDR_HAVE_FLOAT128
FASTCDR_SIZEOF_LONG_DOUBLE = _MotorCommandsWrapper.FASTCDR_SIZEOF_LONG_DOUBLE
import fastdds
class _MotorCommandsSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _MotorCommandsWrapper.delete__MotorCommandsSeq

# Register _MotorCommandsSeq in _MotorCommandsWrapper:
_MotorCommandsWrapper._MotorCommandsSeq_swigregister(_MotorCommandsSeq)
class MotorCommandsSeq(_MotorCommandsSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _MotorCommandsWrapper.delete_MotorCommandsSeq

    def __init__(self, *args):
        _MotorCommandsWrapper.MotorCommandsSeq_swiginit(self, _MotorCommandsWrapper.new_MotorCommandsSeq(*args))

    def __len__(self):
        return _MotorCommandsWrapper.MotorCommandsSeq___len__(self)

    def __getitem__(self, i):
        return _MotorCommandsWrapper.MotorCommandsSeq___getitem__(self, i)

# Register MotorCommandsSeq in _MotorCommandsWrapper:
_MotorCommandsWrapper.MotorCommandsSeq_swigregister(MotorCommandsSeq)
class MotorCommands(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _MotorCommandsWrapper.delete_MotorCommands

    def __init__(self, *args):
        _MotorCommandsWrapper.MotorCommands_swiginit(self, _MotorCommandsWrapper.new_MotorCommands(*args))

    def __eq__(self, x):
        return _MotorCommandsWrapper.MotorCommands___eq__(self, x)

    def __ne__(self, x):
        return _MotorCommandsWrapper.MotorCommands___ne__(self, x)

    def sec(self, *args):
        return _MotorCommandsWrapper.MotorCommands_sec(self, *args)

    def nanosec(self, *args):
        return _MotorCommandsWrapper.MotorCommands_nanosec(self, *args)

    def duty_cycle(self, *args):
        return _MotorCommandsWrapper.MotorCommands_duty_cycle(self, *args)

# Register MotorCommands in _MotorCommandsWrapper:
_MotorCommandsWrapper.MotorCommands_swigregister(MotorCommands)
FASTDDS_GEN_API_VER = _MotorCommandsWrapper.FASTDDS_GEN_API_VER
class MotorCommandsPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _MotorCommandsWrapper.MotorCommandsPubSubType_swiginit(self, _MotorCommandsWrapper.new_MotorCommandsPubSubType())
    __swig_destroy__ = _MotorCommandsWrapper.delete_MotorCommandsPubSubType

    def serialize(self, data, payload, data_representation):
        return _MotorCommandsWrapper.MotorCommandsPubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _MotorCommandsWrapper.MotorCommandsPubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _MotorCommandsWrapper.MotorCommandsPubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _MotorCommandsWrapper.MotorCommandsPubSubType_compute_key(self, *args)

    def create_data(self):
        return _MotorCommandsWrapper.MotorCommandsPubSubType_create_data(self)

    def delete_data(self, data):
        return _MotorCommandsWrapper.MotorCommandsPubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _MotorCommandsWrapper.MotorCommandsPubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _MotorCommandsWrapper.MotorCommandsPubSubType_is_bounded(self)

    def is_plain(self, data_representation):
        return _MotorCommandsWrapper.MotorCommandsPubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _MotorCommandsWrapper.MotorCommandsPubSubType_construct_sample(self, memory)

# Register MotorCommandsPubSubType in _MotorCommandsWrapper:
_MotorCommandsWrapper.MotorCommandsPubSubType_swigregister(MotorCommandsPubSubType)

